### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by Thunderbottom** [AnimbusDev/GEM-Player#15]
Crashes while clicking on top square space of the sidebar. 
Also, crashes while playing certain music files, if you want I can produce logs.

**Comment by AdrianVovk** [comment]
What version are you running?

**Comment by AdrianVovk** [comment]
Yes it crashes if there isn't music playing and you tap the header.

Can you provide more details on the second issue?

**Comment by Thunderbottom** [comment]
Well I'm running the latest version, built from Android Studio. The first crash occurs when music is playing too.

For the second crash, if the song is below 1 min of duration it crashes, also it contains some non-english characters, I guess any of them should help

**Comment by Thunderbottom** [comment]
Text doesn't appear on white background, with blue color. The text is also white so can't see
Also the sidebar is not seen on black background

**Comment by AdrianVovk** [comment]
@balzathor Screenshots please

**Comment by AdrianVovk** [comment]
I'll close this issue for lack of detail

**Comment by Thunderbottom** [comment]
I'll provide details when I'm at home

**Comment by AdrianVovk** [comment]
Ok

**Comment by AdrianVovk** [comment]
Still no details
