### ISSUE TITLE
Notification Reappearing

### ISSUE THREAD

**Issue by AdrianVovk** [AnimbusDev/GEM-Player#16]
Notification reappears when playback is stopped. caused by the system updating the notification AFTER the the stop command (and the stop command stops playback, this is done from onPlaybackStateChanged)

Debug info:
 OS Version: 3.4.42-g5a7e063(eng.eagleeyetom.20150815.100642)
 OS API Level: 22
 Device: victara
 Model (and Product): victara (victara_tmo)
 RELEASE: 5.1.1
 BRAND: motorola
 DISPLAY: $LVY48C
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: motorola

Extra Info: 
 App Version: 0.2.0 Internal

**Comment by Thunderbottom** [comment]
Well, you can add a (x) button to the notification when the player exits or the playing stops, so that the user can close the notifcation if he wants to.

**Comment by AdrianVovk** [comment]
@balzathor It does this on pre-lollipop. I know how to fix the issue already.

**Comment by Thunderbottom** [comment]
I'll take a look at what has to be done :)

**Comment by AdrianVovk** [comment]
@balzathor no need. I already fixed it

**Comment by Thunderbottom** [comment]
:+1:
