### ISSUE TITLE
File missed!

### ISSUE THREAD

**Issue by johncaijing** [AnimbusDev/GEM-Player#17]
In Gradle file,many  proguardFile are marked as 'C:/Users/Adrian/StudioProjects/GEM/mobile/proguard-rules.pro'.But I can't find this file,Please fix this.Thanks a lot.

**Comment by Thunderbottom** [comment]
That's because the proguard rules are on the Dev's PC. You can ask the dev to share that file or just remove that line if you want to, it won't matter much.

**Comment by AdrianVovk** [comment]
@JohnTsaiAndroid here:
https://github.com/Substance-Project/GEM/blob/indev/mobile/proguard-rules.pro

**Comment by johncaijing** [comment]
But there is a file named 'C:/Users/Adrian/Desktop/Programming/ApkSigning.jks' missed!Can you tell me where this file is?Thanks a lot.

**Comment by AdrianVovk** [comment]
@JohnTsaiAndroid No. That file was excluded on purpose. It is the file I use to sign GEM to be able to send it to the play store. No, I won't give you the file as it will be a security risk.
