### ISSUE TITLE
Can't click on song from album view && Switching albums causes crash.

### ISSUE THREAD

**Issue by legacyhardware** [AnimbusDev/GEM-Player#19]
Songs will not play from album view. There isn't a ripple either. using the FAB will play the album though. Song will play from the song tab.

&&

Playing another album while one is already playing causes crash.

Debug info:
 OS Version: 3.4.67-cyanogenmod-g8021b62(eng.hamster.20151025.152226)
 OS API Level: 23
 Device: bacon
 Model (and Product): A0001 (aosp_bacon)
 RELEASE: 6.0
 BRAND: oneplus
 DISPLAY: aosp_bacon-userdebug 6.0 MRA58K eng.hamster.20151025.152226 test-keys
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: bacon
 MANUFACTURER: OnePlus

Extra Info: 
 App Version: 0.2.1
 App Version ID: 13

**Comment by AdrianVovk** [comment]
Can you elaborate on the second issue?

**Comment by legacyhardware** [comment]
@AnimbusDev 
This basically sums up both issues.
https://www.youtube.com/watch?v=YJlBb4hpkA0
