### ISSUE TITLE
Color of Nav drawer text and icons in light theme

### ISSUE THREAD

**Issue by ecols33** [AnimbusDev/GEM-Player#26]
The color of nav drawer text and icons in light theme is white, so you can't see them.

Debug info:
 OS Version: 3.4.42-g835800a(1)
 OS API Level: 22
 Device: victara
 Model (and Product): XT1093 (victara_usc)
 RELEASE: 5.1
 BRAND: motorola
 DISPLAY: LPE23.32-21.7
 CPU_ABI: armeabi-v7a
 CPU_ABI2: armeabi
 HARDWARE: qcom
 MANUFACTURER: motorola

Extra Info: 
 App Version: 0.2.1
 App Version ID: 13

**Comment by AdrianVovk** [comment]
Did you just change theme?

**Comment by AdrianVovk** [comment]
Fixed (Maybe)
