### ISSUE TITLE
The color of text in drawer is too similar to get clearly.Please fix this bug. 

### ISSUE THREAD

**Issue by johncaijing** [AnimbusDev/GEM-Player#28]
that problem like this:![](http://ww1.sinaimg.cn/large/8942f980gw1ey0ccuzjs3j20hi0tdjss.jpg)

**Comment by AdrianVovk** [comment]
Did you just change the theme?

**Comment by johncaijing** [comment]
Yes,I tried different theme.But this problem exist in all of those situations.In my view,you can change the text color to make it different from the drawer's background color.

**Comment by Thunderbottom** [comment]
This exactly is my problem, sorry I couldn't provide screens, I have exams going on.

**Comment by Thunderbottom** [comment]
Also the text in the main screen is also white for white theme, so you can barely see it.

**Comment by AdrianVovk** [comment]
@JohnTsaiAndroid @balzathor I dont think you understand myquestion. Does this happen right after you change the theme or does it persist after you exit GEM (and remove it from mulktitasking) and reopen it?

**Comment by Thunderbottom** [comment]
It persists

**Comment by AdrianVovk** [comment]
@balzathor What android version?

**Comment by johncaijing** [comment]
Android 4.4.4 Genymotion

**Comment by Thunderbottom** [comment]
5.0.1, 5.1.1, 4.4.4 all tested and there's the same problem

**Comment by AdrianVovk** [comment]
I think I fixed this in commit 4618374
