### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by AdrianVovk** [AnimbusDev/GEM-Player#32]
The Marshmallow permissions system doesn't work

**Comment by old-mar** [comment]
It doesn't seem to install at all for me on Marshmallow :/

**Comment by AdrianVovk** [comment]
@cyalins It isntaoos for me... It just crashes on launch if the permissions are disabled

**Comment by AdrianVovk** [comment]
Fixed by 8bc18d511064544dea468bbe7193f5222b8e220e
