### ISSUE TITLE
Can you provide us more details?

### ISSUE THREAD

**Issue by AkshayChordiya** [AnimbusDev/GEM-Player#4]
Your Music Player seems interesting. And I'm excited to know more about it, can you add more information, details about Substance & GEM.
Thank you.

**Comment by legacyhardware** [comment]
Thanks for your interest. :yum:
Updated the readme. Is that enough information?
I plan on writing more about Gem in the Wiki.

**Comment by crutchcorn** [comment]
I think that we should include more screenshots and even possibly GIFs of the animations included in the app shortly after @AnimbusDev works a bit more on what he's currently got up his sleeve

**Comment by legacyhardware** [comment]
@crutchcorn Sounds about right. I'll see about adding more screenshots right now.

**Comment by crutchcorn** [comment]
:+1:
