### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by hamzeyto** [AnimbusDev/GEM-Player#52]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate either here or via email, so I don't have to create issues. Thank you.

**Comment by AdrianVovk** [comment]
Could you please elaborate? What do you mean that you are good at copyrighting?

Also, feel free to make a pull request if you wish. If you'd like to communicate further you can comment on this issue.

Thank you

**Comment by AdrianVovk** [comment]
I would also like to warn you that this project is dead, so you might be doing work that nobody will ever really see

**Comment by hamzeyto** [comment]
okay then
